version: "3.9"

services:
  ollama-1:
    image: ollama/ollama:latest
    container_name: ollama-1
    ports:
      - "11434:11434"
    volumes:
      - ./script/entrypoint-ollama-1.sh:/script/entrypoint.sh
      - ./ollama/ollama-1:/root/.ollama
    environment:
      OLLAMA_MODELS: /root/.ollama
      OLLAMA_KEEP_ALIVE: 4h
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8g
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    entrypoint: ["sh","/script/entrypoint.sh" ]

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9090"

  postgres:
    image: postgres:16
    container_name: Documentation
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: documentation
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  minio_data:
  pg_data: