version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/models:/root/.ollama
    environment:
      OLLAMA_MODELS: /root/.ollama
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 16g
    runtime: nvidia